webapplication/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webapplication.Controllers
{
    public class AlertController : Controller
    {
        // GET: Alert
        public ActionResult Index()
        {
            return View();
        }
    }
}

webapplication/Controllers/AnalysisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MongoDB.Bson;
using MongoDB.Driver;

namespace webapplication.Controllers
{
    public class AnalysisController : Controller
    {
        public async Task<ActionResult> Index()
        {
            var Client = new MongoClient("mongodb://localhost:27017");
            var Database = Client.GetDatabase("chainsapm");
            var collection = Database.GetCollection<ChainsAPM.Models.EntryPoint>("entrypoints");
            var srt = Builders<ChainsAPM.Models.EntryPoint>.Sort.Ascending("Started");
            return View(await collection.Find(x => true).Sort(srt).ToListAsync());
        }

        public async Task<ActionResult> Details(string id)
        {
            var Client = new MongoClient("mongodb://localhost:27017");
            var Database = Client.GetDatabase("chainsapm");
            var collection = Database.GetCollection<ChainsAPM.Models.EntryPoint>("entrypoints");
            return View(await collection.Find(x => x._id == new ObjectId(id)).FirstOrDefaultAsync());
        }
        // GET: Analysis

    }
}

webapplication/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace webapplication.Controllers
{
    public class DashboardController : Controller
    {
        // GET: Dashboard
        public ActionResult Index()
        {
            return View();
        }
    }
}

webapplication/Views/Shared/EntryPointHelper.cshtml
@model ChainsAPM.Interfaces.IStackItem

<ul>
    <li>
        @Html.LabelFor(x => x.Name)
        @if ( Model.Children != null ) {
        @Html.EditorFor(x => x.Children)
        }
    </li>
</ul>

webapplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ChainsAPM - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesomecss")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="icon"
          type="image/png"
          href="~/Content/img/chainslogo_25.png">


    <script type="text/javascript">
        window.appInsights = { queue: [], applicationInsightsId: null, accountId: null, appUserId: null, configUrl: null, start: function (n) { function u(n) { t[n] = function () { var i = arguments; t.queue.push(function () { t[n].apply(t, i) }) } } function f(n, t) { if (n) { var u = r.createElement(i); u.type = "text/javascript"; u.src = n; u.async = !0; u.onload = t; u.onerror = t; r.getElementsByTagName(i)[0].parentNode.appendChild(u) } else t() } var r = document, t = this, i; t.applicationInsightsId = n; u("logEvent"); u("logPageView"); i = "script"; f(t.configUrl, function () { f("//az416426.vo.msecnd.net/scripts/a/ai.0.7.js") }); t.start = function () { } } };

        appInsights.start("07669186-ee7b-4039-b6c0-e1a745215fc1");
        appInsights.logPageView();
    </script>
</head>
<body>
    <div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#"><img src="~/Content/img/chainslogo_50.png" style="padding-right:1em" />ChainsAPM</a>
                </li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Analysis")"><i class="fa fa-flask"></i>Analysis</a></li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Dashboard")"><i class="fa fa-dashboard"></i>Dashboards</a></li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Alert")"><i class="fa fa-bell"></i>Alerts</a></li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Error")"><i class="fa fa-exclamation-circle"></i>Errors</a></li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Error")"><i class="fa fa-file"></i>Logs</a></li>
                <li style="font-size:1.25em"><a href="@Url.Action("Index","Error")"><i class="fa fa-database"></i>Database</a></li>
            </ul>
        </div>

        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        @RenderBody()
                        <hr />
                        <footer>
                            <p>&copy; @DateTime.Now.Year - ChainsAPM</p>
                        </footer>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>